repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14  # Asegúrate de que coincida o sea cercana a la versión en tu toml
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format